[app]
title           = Spelling Sprint League
package.name    = spellingsprint
package.domain  = org.spellingsprint

source.dir      = .
source.include_exts = py,png,jpg,jpeg,json,ttf,otf,kv

version         = 2.0

# Kivy + pygame (no version pin — lets p4a pick a compatible build)
requirements    = python3,kivy==2.3.0,pygame==2.1.3,sdl2,sdl2_image,sdl2_mixer,sdl2_ttf,pillow

orientation     = landscape
fullscreen      = 1

# Icons (generated by make_icon.py in the CI step)
icon.filename        = %(source.dir)s/icon.png
presplash.filename   = %(source.dir)s/presplash.png
presplash.color      = #08081a

# Android settings
android.api          = 33
android.minapi       = 21
android.ndk          = 25b
android.archs        = arm64-v8a
android.permissions  = INTERNET, ACCESS_NETWORK_STATE, WRITE_EXTERNAL_STORAGE, READ_EXTERNAL_STORAGE
android.allow_backup = True

p4a.bootstrap = sdl2

[buildozer]
log_level    = 2
warn_on_root = 1
